### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by taveratch** [bokherus/web-barcamp-bangkhen7#14]
<img width="1373" alt="screen shot 2559-08-31 at 12 42 02 pm" src="https://cloud.githubusercontent.com/assets/8603253/18151655/e46679b4-701a-11e6-9fbf-b404d7321324.png">
<img width="1371" alt="screen shot 2559-08-31 at 12 42 12 pm" src="https://cloud.githubusercontent.com/assets/8603253/18151666/f435e884-701a-11e6-84ab-ee9e271a49b4.png">

**Comment by bokherus** [comment]
done
